1x-electron:
  image: cypress/base:10
  stage: test

  # cache NPM modules using branch name
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - ~/.npm
    - ~/.cache

  before_script:
    - npm ci
    - npm run cy:verify

  script:
    - npm run test:ci:record -- --group 1x-electron

2x-electron-1:
  image: cypress/base:10
  stage: test

  # cache NPM modules using branch name
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - ~/.npm
    - ~/.cache

  before_script:
    - npm ci
    - npm run cy:verify

  script:
    - npm run test:ci:record -- --parallel --group 2x-electron

2x-electron-2:
  image: cypress/base:10
  stage: test

  # cache NPM modules using branch name
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - ~/.npm
    - ~/.cache

  before_script:
    - npm ci
    - npm run cy:verify

  script:
    - npm run test:ci:record -- --parallel --group 2x-electron
