language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

env:
  global:
    - CYPRESS_INSTALL_BINARY=https://cdn.cypress.io/beta/binary/3.1.0/linux64/circle-develop-126933385e6db0ea1f5316f87620a0ddbc18e7bd-32535/cypress.zip
    - CYPRESS_ENV=staging

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

# upload file with stderr
addons:
  artifacts:
    debug: true
    paths:
    - errors

defaults: &defaults
  script:
    #   ## print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - npm start -- --silent &
    # - npm run cy:run -- --record --parallel 2> errors
    # try killing stuck process
    - node timer.js 2> errors
    # kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true
  after_failure:
    - echo "job failed!"
    - cat errors

jobs:
  include:
    # first stage - run all specs using single worker
    - stage: 1x-electron
      <<: *defaults
    # run 2 workers against all specs
    - stage: 2x-electron
      <<: *defaults
    - stage: 2x-electron
      <<: *defaults
    # run tests in parallel by including several test jobs
    - stage: 4x-electron
      <<: *defaults
    - stage: 4x-electron
      <<: *defaults
    - stage: 4x-electron
      <<: *defaults
    - stage: 4x-electron
      <<: *defaults
