language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

env:
  global:
    - CYPRESS_INSTALL_BINARY=https://cdn.cypress.io/beta/binary/3.1.0/linux64/circle-develop-60bc818c4f075df39d6a2326edee47cf363c1d78-32795/cypress.zip
    - CYPRESS_ENV=staging

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

# upload file with stderr
addons:
  artifacts:
    debug: true
    paths:
    - errors

defaults: &defaults
  script:
    #   ## print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - npm start -- --silent &
    # - npm run cy:run -- --record --parallel 2> errors
    # try killing stuck process
    - node timer.js 2> errors
    # kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true
  after_failure:
    - echo "job failed!"
    - cat errors

jobs:
  include:
    # have just a single stage, but control groups via variables
    - stage: test
      env:
        - STAGE_NAME=1x-electron
        - TIMEOUT_SECONDS=900
      <<: *defaults
    # run 2 workers against all specs
    - stage: test
      env:
        - STAGE_NAME=2x-electron
        - TIMEOUT_SECONDS=700
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=2x-electron
        - TIMEOUT_SECONDS=700
      <<: *defaults
    # run tests in parallel by including several test jobs
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
