defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/base:8
      environment:
        ## this enables colors in the output
        TERM: xterm
        CYPRESS_INSTALL_BINARY: https://cdn.cypress.io/beta/binary/3.1.0/linux64/circle-develop-4ead424d4c9e3d65422c71597496539290720057-32310/cypress.zip
        CYPRESS_ENV: staging

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          key: v2-app-{{ .Branch }}
          key: v2-app-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
            - .git
      - run: npm run types
      - persist_to_workspace:
          root: ~/
          paths:
            - app/node_modules
            - .cache
  
  test-electron:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/

      - run: 
          command: npm start
          background: true

      - run: npm run e2e:record -- --parallel --group electron

  test-chrome:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/

      - run: 
          command: npm start
          background: true

      - run: npm run e2e:record -- --parallel --group chrome --browser chrome

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-electron:
          requires:
            - build
      - test-chrome:
          requires:
            - build
