defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome67
      environment:
        ## this enables colors in the output
        TERM: xterm
        CYPRESS_INSTALL_BINARY: https://cdn.cypress.io/beta/binary/3.1.0/linux64/circle-develop-4ead424d4c9e3d65422c71597496539290720057-32310/cypress.zip
        CYPRESS_ENV: staging

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-app-{{ .Branch }}
            - v3-app-
      - run:
          name: Install Dependencies
          command: npm ci
      # run verify and then save cache. Then verified status is cached
      - run: npm run cy:verify
      - save_cache:
          key: v3-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run types
      - persist_to_workspace:
          root: ~/
          paths:
            - app

  test-electron-parallel:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-app-{{ .Branch }}
            - v3-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group electron-parallel

  test-electron-parallel-4:
    <<: *defaults
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-app-{{ .Branch }}
            - v3-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group electron-parallel-4

  test-chrome-parallel:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-app-{{ .Branch }}
            - v3-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group chrome-parallel --browser chrome

  test-electron:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-app-{{ .Branch }}
            - v3-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --group electron

  test-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-app-{{ .Branch }}
            - v3-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --group chrome --browser chrome

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-electron-parallel:
          requires:
            - build
      - test-electron-parallel-4:
          requires:
            - build
      - test-chrome-parallel:
          requires:
            - build
      - test-electron:
          requires:
            - build
      - test-chrome:
          requires:
            - build
