defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome67
      environment:
        ## this enables colors in the output
        TERM: xterm
        CYPRESS_INSTALL_BINARY: https://cdn.cypress.io/beta/binary/3.1.0/linux64/circle-develop-7139868f1cb23b9a3a8189355b6ee738c2f2956e-32884/cypress.zip
        CYPRESS_ENV: staging

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4.2-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v4.2-app-{{ .Branch }}
            - v4.2-app-
      - run:
          name: Install Dependencies
          command: npm ci
      # run verify and then save cache. Then verified status is cached
      - run: npm run cy:verify
      - save_cache:
          key: v4.2-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run types
      - persist_to_workspace:
          root: ~/
          paths:
            - app

  2x-electron:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4.2-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v4.2-app-{{ .Branch }}
            - v4.2-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group $CIRCLE_JOB

  4x-electron:
    <<: *defaults
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4.2-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v4.2-app-{{ .Branch }}
            - v4.2-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group $CIRCLE_JOB

  2x-chrome:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4.2-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v4.2-app-{{ .Branch }}
            - v4.2-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group $CIRCLE_JOB --browser chrome

  1x-electron:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4.2-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v4.2-app-{{ .Branch }}
            - v4.2-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --group $CIRCLE_JOB

  1x-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4.2-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v4.2-app-{{ .Branch }}
            - v4.2-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --group $CIRCLE_JOB --browser chrome

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - 1x-electron:
          requires:
            - build
      - 2x-electron:
          requires:
            - build
      - 4x-electron:
          requires:
            - build
      - 1x-chrome:
          requires:
            - build
      - 2x-chrome:
          requires:
            - build
