defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome67
      environment:
        ## this enables colors in the output
        TERM: xterm

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v5-app-{{ .Branch }}
            - v5-app-
      - run:
          name: Install Dependencies
          command: npm ci
      # run verify and then save cache. Then verified status is cached
      - run: npm run cy:verify
      - save_cache:
          key: v5-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run types
      - persist_to_workspace:
          root: ~/
          paths:
            - app

  1x-electron:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v5-app-{{ .Branch }}
            - v5-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      # run all tests and pass group name (should be "1x-electron" in this case)
      - run: npm run e2e:record -- --group $CIRCLE_JOB

  4x-electron:
    <<: *defaults
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v5-app-{{ .Branch }}
            - v5-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group $CIRCLE_JOB

  2x-chrome:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-app-{{ .Branch }}-{{ checksum "package.json" }}
            - v5-app-{{ .Branch }}
            - v5-app-
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group $CIRCLE_JOB --browser chrome

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # after installing dependencies in the "build" job
      # run all tests in several groups
      #     group "1x-electron"
      - 1x-electron:
          requires:
            - build
      # this group "4x-electron" will load balance all specs
      # and use the built-in Electron browser run them
      - 4x-electron:
          requires:
            - build
      # this group "2x-chrome" will load balance all specs
      # and use Chrome browser to run them
      - 2x-chrome:
          requires:
            - build
