jobs:

  # assuming the job runs on "Hosted Linux Preview" agent

  # Job names can contain alphanumeric characters and '_', cannot start with a number
  - job: Cypress_e2e_tests
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
          displayName: 'Install Node.js'

      # VSTS hosted Linux agents already have a LOT of dependencies preinstalled
      # https://github.com/Microsoft/vsts-agent-docker
      # so we don't have to install all recommended Cypress dependencies
      # https://on.cypress.io/continuous-integration#Dependencies
      - script: apt-get update && apt-get install -y libgconf-2-4
        displayName: 'install dependencies'

      - script: npm ci
        displayName: 'Install NPM dependencies'

      - script: npm run cy:verify
        displayName: 'Cypress verify'

      # The next command starts the server and runs Cypress end-to-end tests against it.
      # The test artifacts (video, screenshots, test output) will be uploaded to Cypress dashboard
      - script: npm run test:ci:record
        displayName: 'Run Cypress tests'
        # To record on Cypress dashboard we need to set CYPRESS_RECORD_KEY environment variable
        # See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
        # Make sure to mark variable CYPRESS_RECORD_KEY secret to avoid accidentally leaking it
