name: Firefox

on: push

jobs:
  firefox:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images
    container: 
      image: cypress/browsers:node13.6.0-chrome80-ff72
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Firefox
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          build: google-chrome --version && firefox --version && npm run build
          start: npm start
          browser: firefox
