name: Using Cypress GH Action
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@e3c95c3
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:8080
